create table tb_participantes (id int8 generated by default as identity, cpf varchar(255), nome varchar(255), opcao varchar(255), primary key (id));
alter table if exists tb_participantes add constraint UK_qa7w15w9673gobe8l6v0rdbie unique (cpf);
alter table if exists tb_participantes add constraint UK_5lsvedwqu2w11xlbnclgxtlqq unique (opcao);
INSERT INTO tb_participantes(nome, cpf, opcao) VALUES ('Leandro', '111.222.333-44', 'Bolo de rolo');
INSERT INTO tb_participantes(nome, cpf, opcao) VALUES ('Carolina', '222.222.222-44', 'Pão');
INSERT INTO tb_participantes(nome, cpf, opcao) VALUES ('Ana Clara', '333.333.333-44', 'Queijo');
INSERT INTO tb_participantes(nome, cpf, opcao) VALUES ('Joanna', '444.444.444-44', 'Bolo');
